# Generated by Django 4.0.6 on 2022-07-14 06:58

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='admin', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=255, populate_from='title', unique=True)),
                ('img1', models.FileField(default=None, max_length=500, upload_to='blog_images/')),
                ('img2', models.FileField(default=None, max_length=500, upload_to='blog_images/')),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
