# Generated by Django 4.0.6 on 2022-07-14 07:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='body',
            field=tinymce.models.HTMLField(default=None),
        ),
    ]
