# Generated by Django 4.0.6 on 2022-07-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
