# Generated by Django 4.0.6 on 2022-07-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=355, null=True),
        ),
    ]
