# Generated by Django 4.0.6 on 2022-07-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blogs_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(choices=[('physics', 'physics'), ('ai', 'ai'), ('ml', 'ml'), ('technology', 'technology'), ('mathematics', 'mathematics'), ('python', 'python'), ('universe', 'universe'), ('sports', 'sports'), ('music', 'music'), ('entertainment', 'entertainment')], default='physics', max_length=255),
        ),
    ]
