# Generated by Django 4.0.6 on 2022-07-14 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_blogs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='published_on',
            field=models.DateTimeField(default=datetime.date(2022, 7, 14)),
        ),
    ]
