# Generated by Django 4.0.6 on 2022-07-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blogs_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
