# Generated by Django 4.0.6 on 2022-07-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_blogs_published_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=355)),
                ('description', models.CharField(max_length=255)),
                ('categoryImg', models.FileField(default=None, max_length=500, upload_to='category_images/')),
                ('published_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
