# Generated by Django 4.0.6 on 2022-07-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_blogcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='authorImg',
            field=models.FileField(default='author/admin.jpg', max_length=500, upload_to='author/'),
        ),
    ]
